import Head from 'next/head';
import Description from 'components/home/description/Description';
import Container from 'components/home/container/Container';
import Steps from 'components/home/steps/Steps';
import Ershad from 'components/home/ershad/Ershad';
import Fingerprint from 'components/home/fingerprint/Fingerprint';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Container>
					<Description />
					<Steps />
					<Ershad />
					<Fingerprint />
				</Container>
			</main>
		</>
	);
}
